# Generated by Django 5.2.6 on 2025-09-18 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heartbeats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heartrate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
